_target_: medical_imaging_imf.models.unet_hf.unet_hugging_face.Unet

dim : 128
init_dim : null
out_dim : null
dim_mults : [1, 1, 2]
channels : 1

self_condition : False
resnet_block_groups : 4
n_block_klass : 2