_partial_: true
_target_: torch.utils.data.DataLoader
batch_size: 2
prefetch_factor: 1
num_workers: 1
shuffle: true
pin_memory: true
drop_last: false
collate_fn: 
  _target_: medical_imaging_imf.data.utils.collate_fn
  _partial_: true